version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
    - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  web:
    ipc: host
    build: .
    ports:
      - "6969:6969"
    links:
      - redis
    depends_on:
      - redis
    restart: unless-stopped
